// Code generated by MockGen. DO NOT EDIT.
// Source: C:/Users/MihailPestrikov/GolandProjects/avito-backend-trainee-assignment-spring-2025/internal/api/handlers/interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "avito-backend-trainee-assignment-spring-2025/internal/domain/models"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockUserServiceInterface is a mock of UserServiceInterface interface.
type MockUserServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceInterfaceMockRecorder
}

// MockUserServiceInterfaceMockRecorder is the mock recorder for MockUserServiceInterface.
type MockUserServiceInterfaceMockRecorder struct {
	mock *MockUserServiceInterface
}

// NewMockUserServiceInterface creates a new mock instance.
func NewMockUserServiceInterface(ctrl *gomock.Controller) *MockUserServiceInterface {
	mock := &MockUserServiceInterface{ctrl: ctrl}
	mock.recorder = &MockUserServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServiceInterface) EXPECT() *MockUserServiceInterfaceMockRecorder {
	return m.recorder
}

// DummyLogin mocks base method.
func (m *MockUserServiceInterface) DummyLogin(role string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DummyLogin", role)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DummyLogin indicates an expected call of DummyLogin.
func (mr *MockUserServiceInterfaceMockRecorder) DummyLogin(role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DummyLogin", reflect.TypeOf((*MockUserServiceInterface)(nil).DummyLogin), role)
}

// GetUserByID mocks base method.
func (m *MockUserServiceInterface) GetUserByID(ctx context.Context, id uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserServiceInterfaceMockRecorder) GetUserByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserServiceInterface)(nil).GetUserByID), ctx, id)
}

// Login mocks base method.
func (m *MockUserServiceInterface) Login(ctx context.Context, email, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserServiceInterfaceMockRecorder) Login(ctx, email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserServiceInterface)(nil).Login), ctx, email, password)
}

// Register mocks base method.
func (m *MockUserServiceInterface) Register(ctx context.Context, email, password, role string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, email, password, role)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockUserServiceInterfaceMockRecorder) Register(ctx, email, password, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUserServiceInterface)(nil).Register), ctx, email, password, role)
}

// MockPVZServiceInterface is a mock of PVZServiceInterface interface.
type MockPVZServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPVZServiceInterfaceMockRecorder
}

// MockPVZServiceInterfaceMockRecorder is the mock recorder for MockPVZServiceInterface.
type MockPVZServiceInterfaceMockRecorder struct {
	mock *MockPVZServiceInterface
}

// NewMockPVZServiceInterface creates a new mock instance.
func NewMockPVZServiceInterface(ctrl *gomock.Controller) *MockPVZServiceInterface {
	mock := &MockPVZServiceInterface{ctrl: ctrl}
	mock.recorder = &MockPVZServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPVZServiceInterface) EXPECT() *MockPVZServiceInterfaceMockRecorder {
	return m.recorder
}

// CreatePVZ mocks base method.
func (m *MockPVZServiceInterface) CreatePVZ(ctx context.Context, city string) (*models.PVZ, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePVZ", ctx, city)
	ret0, _ := ret[0].(*models.PVZ)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePVZ indicates an expected call of CreatePVZ.
func (mr *MockPVZServiceInterfaceMockRecorder) CreatePVZ(ctx, city interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePVZ", reflect.TypeOf((*MockPVZServiceInterface)(nil).CreatePVZ), ctx, city)
}

// GetAllPVZ mocks base method.
func (m *MockPVZServiceInterface) GetAllPVZ(ctx context.Context, filter models.PVZFilter) ([]*models.PVZ, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPVZ", ctx, filter)
	ret0, _ := ret[0].([]*models.PVZ)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllPVZ indicates an expected call of GetAllPVZ.
func (mr *MockPVZServiceInterfaceMockRecorder) GetAllPVZ(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPVZ", reflect.TypeOf((*MockPVZServiceInterface)(nil).GetAllPVZ), ctx, filter)
}

// GetAllPVZWithReceptions mocks base method.
func (m *MockPVZServiceInterface) GetAllPVZWithReceptions(ctx context.Context, filter models.PVZFilter) ([]models.PVZWithReceptions, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPVZWithReceptions", ctx, filter)
	ret0, _ := ret[0].([]models.PVZWithReceptions)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllPVZWithReceptions indicates an expected call of GetAllPVZWithReceptions.
func (mr *MockPVZServiceInterfaceMockRecorder) GetAllPVZWithReceptions(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPVZWithReceptions", reflect.TypeOf((*MockPVZServiceInterface)(nil).GetAllPVZWithReceptions), ctx, filter)
}

// GetPVZByID mocks base method.
func (m *MockPVZServiceInterface) GetPVZByID(ctx context.Context, id uuid.UUID) (*models.PVZ, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPVZByID", ctx, id)
	ret0, _ := ret[0].(*models.PVZ)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPVZByID indicates an expected call of GetPVZByID.
func (mr *MockPVZServiceInterfaceMockRecorder) GetPVZByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPVZByID", reflect.TypeOf((*MockPVZServiceInterface)(nil).GetPVZByID), ctx, id)
}

// MockReceptionServiceInterface is a mock of ReceptionServiceInterface interface.
type MockReceptionServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockReceptionServiceInterfaceMockRecorder
}

// MockReceptionServiceInterfaceMockRecorder is the mock recorder for MockReceptionServiceInterface.
type MockReceptionServiceInterfaceMockRecorder struct {
	mock *MockReceptionServiceInterface
}

// NewMockReceptionServiceInterface creates a new mock instance.
func NewMockReceptionServiceInterface(ctrl *gomock.Controller) *MockReceptionServiceInterface {
	mock := &MockReceptionServiceInterface{ctrl: ctrl}
	mock.recorder = &MockReceptionServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReceptionServiceInterface) EXPECT() *MockReceptionServiceInterfaceMockRecorder {
	return m.recorder
}

// CloseReception mocks base method.
func (m *MockReceptionServiceInterface) CloseReception(ctx context.Context, pvzID uuid.UUID) (*models.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseReception", ctx, pvzID)
	ret0, _ := ret[0].(*models.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloseReception indicates an expected call of CloseReception.
func (mr *MockReceptionServiceInterfaceMockRecorder) CloseReception(ctx, pvzID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseReception", reflect.TypeOf((*MockReceptionServiceInterface)(nil).CloseReception), ctx, pvzID)
}

// CreateReception mocks base method.
func (m *MockReceptionServiceInterface) CreateReception(ctx context.Context, pvzID uuid.UUID) (*models.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReception", ctx, pvzID)
	ret0, _ := ret[0].(*models.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReception indicates an expected call of CreateReception.
func (mr *MockReceptionServiceInterfaceMockRecorder) CreateReception(ctx, pvzID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReception", reflect.TypeOf((*MockReceptionServiceInterface)(nil).CreateReception), ctx, pvzID)
}

// GetLastActiveReception mocks base method.
func (m *MockReceptionServiceInterface) GetLastActiveReception(ctx context.Context, pvzID uuid.UUID) (*models.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastActiveReception", ctx, pvzID)
	ret0, _ := ret[0].(*models.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastActiveReception indicates an expected call of GetLastActiveReception.
func (mr *MockReceptionServiceInterfaceMockRecorder) GetLastActiveReception(ctx, pvzID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastActiveReception", reflect.TypeOf((*MockReceptionServiceInterface)(nil).GetLastActiveReception), ctx, pvzID)
}

// GetLastReception mocks base method.
func (m *MockReceptionServiceInterface) GetLastReception(ctx context.Context, pvzID uuid.UUID) (*models.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastReception", ctx, pvzID)
	ret0, _ := ret[0].(*models.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastReception indicates an expected call of GetLastReception.
func (mr *MockReceptionServiceInterfaceMockRecorder) GetLastReception(ctx, pvzID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastReception", reflect.TypeOf((*MockReceptionServiceInterface)(nil).GetLastReception), ctx, pvzID)
}

// GetReceptionByID mocks base method.
func (m *MockReceptionServiceInterface) GetReceptionByID(ctx context.Context, id uuid.UUID) (*models.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReceptionByID", ctx, id)
	ret0, _ := ret[0].(*models.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReceptionByID indicates an expected call of GetReceptionByID.
func (mr *MockReceptionServiceInterfaceMockRecorder) GetReceptionByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReceptionByID", reflect.TypeOf((*MockReceptionServiceInterface)(nil).GetReceptionByID), ctx, id)
}

// MockProductServiceInterface is a mock of ProductServiceInterface interface.
type MockProductServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProductServiceInterfaceMockRecorder
}

// MockProductServiceInterfaceMockRecorder is the mock recorder for MockProductServiceInterface.
type MockProductServiceInterfaceMockRecorder struct {
	mock *MockProductServiceInterface
}

// NewMockProductServiceInterface creates a new mock instance.
func NewMockProductServiceInterface(ctrl *gomock.Controller) *MockProductServiceInterface {
	mock := &MockProductServiceInterface{ctrl: ctrl}
	mock.recorder = &MockProductServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductServiceInterface) EXPECT() *MockProductServiceInterfaceMockRecorder {
	return m.recorder
}

// AddProduct mocks base method.
func (m *MockProductServiceInterface) AddProduct(ctx context.Context, productType string, pvzID uuid.UUID) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProduct", ctx, productType, pvzID)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddProduct indicates an expected call of AddProduct.
func (mr *MockProductServiceInterfaceMockRecorder) AddProduct(ctx, productType, pvzID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProduct", reflect.TypeOf((*MockProductServiceInterface)(nil).AddProduct), ctx, productType, pvzID)
}

// DeleteLastProduct mocks base method.
func (m *MockProductServiceInterface) DeleteLastProduct(ctx context.Context, pvzID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLastProduct", ctx, pvzID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLastProduct indicates an expected call of DeleteLastProduct.
func (mr *MockProductServiceInterfaceMockRecorder) DeleteLastProduct(ctx, pvzID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLastProduct", reflect.TypeOf((*MockProductServiceInterface)(nil).DeleteLastProduct), ctx, pvzID)
}

// GetProductByID mocks base method.
func (m *MockProductServiceInterface) GetProductByID(ctx context.Context, id uuid.UUID) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByID", ctx, id)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByID indicates an expected call of GetProductByID.
func (mr *MockProductServiceInterfaceMockRecorder) GetProductByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByID", reflect.TypeOf((*MockProductServiceInterface)(nil).GetProductByID), ctx, id)
}

// GetProductsByReceptionID mocks base method.
func (m *MockProductServiceInterface) GetProductsByReceptionID(ctx context.Context, receptionID uuid.UUID) ([]models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductsByReceptionID", ctx, receptionID)
	ret0, _ := ret[0].([]models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductsByReceptionID indicates an expected call of GetProductsByReceptionID.
func (mr *MockProductServiceInterfaceMockRecorder) GetProductsByReceptionID(ctx, receptionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductsByReceptionID", reflect.TypeOf((*MockProductServiceInterface)(nil).GetProductsByReceptionID), ctx, receptionID)
}
