// Code generated by MockGen. DO NOT EDIT.
// Source: C:/Users/MihailPestrikov/GolandProjects/avito-backend-trainee-assignment-spring-2025/internal/domain/interfaces/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	interfaces "avito-backend-trainee-assignment-spring-2025/internal/domain/interfaces"
	models "avito-backend-trainee-assignment-spring-2025/internal/domain/models"
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockProductRepository is a mock of ProductRepository interface.
type MockProductRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryMockRecorder
}

// MockProductRepositoryMockRecorder is the mock recorder for MockProductRepository.
type MockProductRepositoryMockRecorder struct {
	mock *MockProductRepository
}

// NewMockProductRepository creates a new mock instance.
func NewMockProductRepository(ctrl *gomock.Controller) *MockProductRepository {
	mock := &MockProductRepository{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepository) EXPECT() *MockProductRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProductRepository) Create(ctx context.Context, product *models.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProductRepositoryMockRecorder) Create(ctx, product interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProductRepository)(nil).Create), ctx, product)
}

// DeleteLastFromReception mocks base method.
func (m *MockProductRepository) DeleteLastFromReception(ctx context.Context, receptionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLastFromReception", ctx, receptionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLastFromReception indicates an expected call of DeleteLastFromReception.
func (mr *MockProductRepositoryMockRecorder) DeleteLastFromReception(ctx, receptionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLastFromReception", reflect.TypeOf((*MockProductRepository)(nil).DeleteLastFromReception), ctx, receptionID)
}

// GetByID mocks base method.
func (m *MockProductRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockProductRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockProductRepository)(nil).GetByID), ctx, id)
}

// GetByReceptionID mocks base method.
func (m *MockProductRepository) GetByReceptionID(ctx context.Context, receptionID uuid.UUID) ([]models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByReceptionID", ctx, receptionID)
	ret0, _ := ret[0].([]models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByReceptionID indicates an expected call of GetByReceptionID.
func (mr *MockProductRepositoryMockRecorder) GetByReceptionID(ctx, receptionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByReceptionID", reflect.TypeOf((*MockProductRepository)(nil).GetByReceptionID), ctx, receptionID)
}

// MockTxProductRepository is a mock of TxProductRepository interface.
type MockTxProductRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTxProductRepositoryMockRecorder
}

// MockTxProductRepositoryMockRecorder is the mock recorder for MockTxProductRepository.
type MockTxProductRepositoryMockRecorder struct {
	mock *MockTxProductRepository
}

// NewMockTxProductRepository creates a new mock instance.
func NewMockTxProductRepository(ctrl *gomock.Controller) *MockTxProductRepository {
	mock := &MockTxProductRepository{ctrl: ctrl}
	mock.recorder = &MockTxProductRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxProductRepository) EXPECT() *MockTxProductRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTxProductRepository) Create(ctx context.Context, product *models.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTxProductRepositoryMockRecorder) Create(ctx, product interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTxProductRepository)(nil).Create), ctx, product)
}

// DeleteLastFromReception mocks base method.
func (m *MockTxProductRepository) DeleteLastFromReception(ctx context.Context, receptionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLastFromReception", ctx, receptionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLastFromReception indicates an expected call of DeleteLastFromReception.
func (mr *MockTxProductRepositoryMockRecorder) DeleteLastFromReception(ctx, receptionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLastFromReception", reflect.TypeOf((*MockTxProductRepository)(nil).DeleteLastFromReception), ctx, receptionID)
}

// GetByID mocks base method.
func (m *MockTxProductRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTxProductRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTxProductRepository)(nil).GetByID), ctx, id)
}

// GetByReceptionID mocks base method.
func (m *MockTxProductRepository) GetByReceptionID(ctx context.Context, receptionID uuid.UUID) ([]models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByReceptionID", ctx, receptionID)
	ret0, _ := ret[0].([]models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByReceptionID indicates an expected call of GetByReceptionID.
func (mr *MockTxProductRepositoryMockRecorder) GetByReceptionID(ctx, receptionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByReceptionID", reflect.TypeOf((*MockTxProductRepository)(nil).GetByReceptionID), ctx, receptionID)
}

// WithTx mocks base method.
func (m *MockTxProductRepository) WithTx(tx *sql.Tx) interfaces.ProductRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(interfaces.ProductRepository)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockTxProductRepositoryMockRecorder) WithTx(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockTxProductRepository)(nil).WithTx), tx)
}

// MockReceptionRepository is a mock of ReceptionRepository interface.
type MockReceptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReceptionRepositoryMockRecorder
}

// MockReceptionRepositoryMockRecorder is the mock recorder for MockReceptionRepository.
type MockReceptionRepositoryMockRecorder struct {
	mock *MockReceptionRepository
}

// NewMockReceptionRepository creates a new mock instance.
func NewMockReceptionRepository(ctrl *gomock.Controller) *MockReceptionRepository {
	mock := &MockReceptionRepository{ctrl: ctrl}
	mock.recorder = &MockReceptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReceptionRepository) EXPECT() *MockReceptionRepositoryMockRecorder {
	return m.recorder
}

// CloseReception mocks base method.
func (m *MockReceptionRepository) CloseReception(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseReception", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseReception indicates an expected call of CloseReception.
func (mr *MockReceptionRepositoryMockRecorder) CloseReception(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseReception", reflect.TypeOf((*MockReceptionRepository)(nil).CloseReception), ctx, id)
}

// Create mocks base method.
func (m *MockReceptionRepository) Create(ctx context.Context, reception *models.Reception) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, reception)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockReceptionRepositoryMockRecorder) Create(ctx, reception interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReceptionRepository)(nil).Create), ctx, reception)
}

// GetByID mocks base method.
func (m *MockReceptionRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockReceptionRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockReceptionRepository)(nil).GetByID), ctx, id)
}

// GetLastActiveByPVZID mocks base method.
func (m *MockReceptionRepository) GetLastActiveByPVZID(ctx context.Context, pvzID uuid.UUID) (*models.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastActiveByPVZID", ctx, pvzID)
	ret0, _ := ret[0].(*models.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastActiveByPVZID indicates an expected call of GetLastActiveByPVZID.
func (mr *MockReceptionRepositoryMockRecorder) GetLastActiveByPVZID(ctx, pvzID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastActiveByPVZID", reflect.TypeOf((*MockReceptionRepository)(nil).GetLastActiveByPVZID), ctx, pvzID)
}

// GetLastReceptionByPVZID mocks base method.
func (m *MockReceptionRepository) GetLastReceptionByPVZID(ctx context.Context, pvzID uuid.UUID) (*models.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastReceptionByPVZID", ctx, pvzID)
	ret0, _ := ret[0].(*models.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastReceptionByPVZID indicates an expected call of GetLastReceptionByPVZID.
func (mr *MockReceptionRepositoryMockRecorder) GetLastReceptionByPVZID(ctx, pvzID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastReceptionByPVZID", reflect.TypeOf((*MockReceptionRepository)(nil).GetLastReceptionByPVZID), ctx, pvzID)
}

// MockTxReceptionRepository is a mock of TxReceptionRepository interface.
type MockTxReceptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTxReceptionRepositoryMockRecorder
}

// MockTxReceptionRepositoryMockRecorder is the mock recorder for MockTxReceptionRepository.
type MockTxReceptionRepositoryMockRecorder struct {
	mock *MockTxReceptionRepository
}

// NewMockTxReceptionRepository creates a new mock instance.
func NewMockTxReceptionRepository(ctrl *gomock.Controller) *MockTxReceptionRepository {
	mock := &MockTxReceptionRepository{ctrl: ctrl}
	mock.recorder = &MockTxReceptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxReceptionRepository) EXPECT() *MockTxReceptionRepositoryMockRecorder {
	return m.recorder
}

// CloseReception mocks base method.
func (m *MockTxReceptionRepository) CloseReception(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseReception", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseReception indicates an expected call of CloseReception.
func (mr *MockTxReceptionRepositoryMockRecorder) CloseReception(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseReception", reflect.TypeOf((*MockTxReceptionRepository)(nil).CloseReception), ctx, id)
}

// Create mocks base method.
func (m *MockTxReceptionRepository) Create(ctx context.Context, reception *models.Reception) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, reception)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTxReceptionRepositoryMockRecorder) Create(ctx, reception interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTxReceptionRepository)(nil).Create), ctx, reception)
}

// GetByID mocks base method.
func (m *MockTxReceptionRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTxReceptionRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTxReceptionRepository)(nil).GetByID), ctx, id)
}

// GetLastActiveByPVZID mocks base method.
func (m *MockTxReceptionRepository) GetLastActiveByPVZID(ctx context.Context, pvzID uuid.UUID) (*models.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastActiveByPVZID", ctx, pvzID)
	ret0, _ := ret[0].(*models.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastActiveByPVZID indicates an expected call of GetLastActiveByPVZID.
func (mr *MockTxReceptionRepositoryMockRecorder) GetLastActiveByPVZID(ctx, pvzID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastActiveByPVZID", reflect.TypeOf((*MockTxReceptionRepository)(nil).GetLastActiveByPVZID), ctx, pvzID)
}

// GetLastReceptionByPVZID mocks base method.
func (m *MockTxReceptionRepository) GetLastReceptionByPVZID(ctx context.Context, pvzID uuid.UUID) (*models.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastReceptionByPVZID", ctx, pvzID)
	ret0, _ := ret[0].(*models.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastReceptionByPVZID indicates an expected call of GetLastReceptionByPVZID.
func (mr *MockTxReceptionRepositoryMockRecorder) GetLastReceptionByPVZID(ctx, pvzID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastReceptionByPVZID", reflect.TypeOf((*MockTxReceptionRepository)(nil).GetLastReceptionByPVZID), ctx, pvzID)
}

// WithTx mocks base method.
func (m *MockTxReceptionRepository) WithTx(tx *sql.Tx) interfaces.ReceptionRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(interfaces.ReceptionRepository)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockTxReceptionRepositoryMockRecorder) WithTx(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockTxReceptionRepository)(nil).WithTx), tx)
}

// MockPVZRepository is a mock of PVZRepository interface.
type MockPVZRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPVZRepositoryMockRecorder
}

// MockPVZRepositoryMockRecorder is the mock recorder for MockPVZRepository.
type MockPVZRepositoryMockRecorder struct {
	mock *MockPVZRepository
}

// NewMockPVZRepository creates a new mock instance.
func NewMockPVZRepository(ctrl *gomock.Controller) *MockPVZRepository {
	mock := &MockPVZRepository{ctrl: ctrl}
	mock.recorder = &MockPVZRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPVZRepository) EXPECT() *MockPVZRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPVZRepository) Create(ctx context.Context, pvz *models.PVZ) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, pvz)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPVZRepositoryMockRecorder) Create(ctx, pvz interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPVZRepository)(nil).Create), ctx, pvz)
}

// GetAll mocks base method.
func (m *MockPVZRepository) GetAll(ctx context.Context, filter models.PVZFilter) ([]*models.PVZ, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, filter)
	ret0, _ := ret[0].([]*models.PVZ)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockPVZRepositoryMockRecorder) GetAll(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPVZRepository)(nil).GetAll), ctx, filter)
}

// GetAllWithReceptions mocks base method.
func (m *MockPVZRepository) GetAllWithReceptions(ctx context.Context, filter models.PVZFilter) ([]models.PVZWithReceptions, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWithReceptions", ctx, filter)
	ret0, _ := ret[0].([]models.PVZWithReceptions)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllWithReceptions indicates an expected call of GetAllWithReceptions.
func (mr *MockPVZRepositoryMockRecorder) GetAllWithReceptions(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWithReceptions", reflect.TypeOf((*MockPVZRepository)(nil).GetAllWithReceptions), ctx, filter)
}

// GetByID mocks base method.
func (m *MockPVZRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.PVZ, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.PVZ)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPVZRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPVZRepository)(nil).GetByID), ctx, id)
}

// MockTxPVZRepository is a mock of TxPVZRepository interface.
type MockTxPVZRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTxPVZRepositoryMockRecorder
}

// MockTxPVZRepositoryMockRecorder is the mock recorder for MockTxPVZRepository.
type MockTxPVZRepositoryMockRecorder struct {
	mock *MockTxPVZRepository
}

// NewMockTxPVZRepository creates a new mock instance.
func NewMockTxPVZRepository(ctrl *gomock.Controller) *MockTxPVZRepository {
	mock := &MockTxPVZRepository{ctrl: ctrl}
	mock.recorder = &MockTxPVZRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxPVZRepository) EXPECT() *MockTxPVZRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTxPVZRepository) Create(ctx context.Context, pvz *models.PVZ) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, pvz)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTxPVZRepositoryMockRecorder) Create(ctx, pvz interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTxPVZRepository)(nil).Create), ctx, pvz)
}

// GetAll mocks base method.
func (m *MockTxPVZRepository) GetAll(ctx context.Context, filter models.PVZFilter) ([]*models.PVZ, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, filter)
	ret0, _ := ret[0].([]*models.PVZ)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockTxPVZRepositoryMockRecorder) GetAll(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockTxPVZRepository)(nil).GetAll), ctx, filter)
}

// GetAllWithReceptions mocks base method.
func (m *MockTxPVZRepository) GetAllWithReceptions(ctx context.Context, filter models.PVZFilter) ([]models.PVZWithReceptions, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWithReceptions", ctx, filter)
	ret0, _ := ret[0].([]models.PVZWithReceptions)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllWithReceptions indicates an expected call of GetAllWithReceptions.
func (mr *MockTxPVZRepositoryMockRecorder) GetAllWithReceptions(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWithReceptions", reflect.TypeOf((*MockTxPVZRepository)(nil).GetAllWithReceptions), ctx, filter)
}

// GetByID mocks base method.
func (m *MockTxPVZRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.PVZ, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.PVZ)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTxPVZRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTxPVZRepository)(nil).GetByID), ctx, id)
}

// WithTx mocks base method.
func (m *MockTxPVZRepository) WithTx(tx *sql.Tx) interfaces.PVZRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(interfaces.PVZRepository)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockTxPVZRepositoryMockRecorder) WithTx(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockTxPVZRepository)(nil).WithTx), tx)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, user)
}

// Delete mocks base method.
func (m *MockUserRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserRepository)(nil).Delete), ctx, id)
}

// GetByEmail mocks base method.
func (m *MockUserRepository) GetByEmail(ctx context.Context, email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryMockRecorder) GetByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, id)
}

// MockTxUserRepository is a mock of TxUserRepository interface.
type MockTxUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTxUserRepositoryMockRecorder
}

// MockTxUserRepositoryMockRecorder is the mock recorder for MockTxUserRepository.
type MockTxUserRepositoryMockRecorder struct {
	mock *MockTxUserRepository
}

// NewMockTxUserRepository creates a new mock instance.
func NewMockTxUserRepository(ctrl *gomock.Controller) *MockTxUserRepository {
	mock := &MockTxUserRepository{ctrl: ctrl}
	mock.recorder = &MockTxUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxUserRepository) EXPECT() *MockTxUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTxUserRepository) Create(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTxUserRepositoryMockRecorder) Create(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTxUserRepository)(nil).Create), ctx, user)
}

// Delete mocks base method.
func (m *MockTxUserRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTxUserRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTxUserRepository)(nil).Delete), ctx, id)
}

// GetByEmail mocks base method.
func (m *MockTxUserRepository) GetByEmail(ctx context.Context, email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockTxUserRepositoryMockRecorder) GetByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockTxUserRepository)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockTxUserRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTxUserRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTxUserRepository)(nil).GetByID), ctx, id)
}

// WithTx mocks base method.
func (m *MockTxUserRepository) WithTx(tx *sql.Tx) interfaces.UserRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(interfaces.UserRepository)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockTxUserRepositoryMockRecorder) WithTx(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockTxUserRepository)(nil).WithTx), tx)
}
